// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYbVxyL2RFRaLyvBCBBAqNO9ZXxk8PYO0',
    appId: '1:873822631396:web:5df338b29b3cd9a631c3f1',
    messagingSenderId: '873822631396',
    projectId: 'mcqmyapp',
    authDomain: 'mcqmyapp.firebaseapp.com',
    storageBucket: 'mcqmyapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc7xTY3nbuXZfsoNndwrm-tMm3O4JL7L8',
    appId: '1:873822631396:android:87a4477b1731d8c031c3f1',
    messagingSenderId: '873822631396',
    projectId: 'mcqmyapp',
    storageBucket: 'mcqmyapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2Kzuqxf_mthDLGVtvKlPzC7kVHF4rso8',
    appId: '1:873822631396:ios:eeb556f08a1ca0d131c3f1',
    messagingSenderId: '873822631396',
    projectId: 'mcqmyapp',
    storageBucket: 'mcqmyapp.appspot.com',
    iosClientId: '873822631396-mrdhkb99bcu98m4i5v9ftq8cl9kpfq2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.messageapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2Kzuqxf_mthDLGVtvKlPzC7kVHF4rso8',
    appId: '1:873822631396:ios:eeb556f08a1ca0d131c3f1',
    messagingSenderId: '873822631396',
    projectId: 'mcqmyapp',
    storageBucket: 'mcqmyapp.appspot.com',
    iosClientId: '873822631396-mrdhkb99bcu98m4i5v9ftq8cl9kpfq2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.messageapp',
  );
}
